name: Hello World
on: 
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: First cmd run
        run: |
          echo "Hello World"
          echo "Second line"